# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c52194d12514593aba2971b6a1df418a"
application_url = "https://YOUR-RENDER-APP.onrender.com"
embedded = true
name = "shoppable-instagram-feed"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://YOUR-RENDER-APP.onrender.com/auth/callback" ]

[webhooks]
api_version = "2026-10"

[build]
automatically_update_urls_on_dev = true
